name: sm_cli
description: A Flutter Clean Architecture CLI generator for scalable production apps. Supports Riverpod, Bloc, GetX, Provider — with GoRouter, Dio, themes, and feature-based clean structure.
version: 1.0.21

homepage: https://github.com/flutterbysunny/sm_cli
repository: https://github.com/flutterbysunny/sm_cli
issue_tracker: https://github.com/flutterbysunny/sm_cli/issues
documentation: https://github.com/flutterbysunny/sm_cli#readme

topics:
  - flutter
  - cli
  - clean-architecture
  - code-generator
  - riverpod
  - AI

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  sm: sm_cli

dependencies:
  path: ^1.9.0
  args: ^2.7.0
  io: ^1.0.5
  interact: ^2.2.0
  http: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6